<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height


        Label:
            id: 'lbl'
            text:
                ('[b][color=faaaaa]Hello[/color] world[/b]')
            markup: True
            font_size: '14pt'
            
        Button:
            text: 'CircleK'
            on_press: app.circle()
            background_color: 1, .3, .4, .85



