#:kivy 1.0
<MyLayout>:
    canvas.before:
        Color:
            rgba: (.2,0,.1,1)
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        colour: 


        Label:
            id: lbl
            markup: True
            font_size: '14pt'
            
        Button:
            text: 'CircleK'
            on_press: root.circle()
            background_color: 1, .3, .4, .85



